services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true

<<<<<<< HEAD
#  frontend:
#    depends_on:
#      - app
#    build:
#      context: ./Frontend/easy-planner
#      dockerfile: Dockerfile
#    restart: unless-stopped
#    ports:
#      - "4200:4200"

volumes:
  db:
=======
  frontend:
    depends_on:
      - app
    build:
      context: ./Frontend/easy-planner
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:4200"

volumes:
  db:
>>>>>>> a16c701e6cc1ce933ecaa7168ea8ac7c807bf4f3
