# .github/workflows/ci.yml
name: CI Monorepo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-ci:
    name: Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend/easy-planner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Auto-format code (Prettier)
        run: npm run format

      - name: Vérifier le formatage (Prettier)
        run: npm run format:check

      - name: Auto-fix lint errors
        run: npm run lint:fix

      - name: Lancer le lint
        run: npm run lint

      # no test for the moment
      # - name: Lancer les tests
      #  run: npm run test

      - name: Générer le build production
        run: npm run build

  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Auto-format code (Prettier)
        run: npm run format

      - name: Vérifier le formatage (Prettier)
        run: npm run format:check

      - name: Auto-fix lint errors
        run: npm run lint:fix

      - name: Lancer le lint
        run: npm run lint

      - name: Lancer les tests
        run: npm run test

  deploy:
    name: Deploy Frontend to GitHub Pages
    runs-on: ubuntu-latest
    needs: [frontend-ci, backend-ci]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend/easy-planner

      - name: Build production
        run: |
          npm install
          npx ng build \
            --configuration=production \
            --output-path=www \
            --base-href=./ \
            --deploy-url=./
        working-directory: ./Frontend/easy-planner

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./Frontend/easy-planner/www/browser
          force_orphan: true
